export const ADD_TODO_DATA_REQUEST = '@@ADD_TODO_DATA_REQUEST'
export const ADD_TODO_DATA = '@@ADD_TODO_DATA'
export const DELETE_FROM_TODOLIST = '@@DELETE_FROM_TODOLIST'
export const GET_TODOLIST_DATA_REQUEST = '@@GET_TODOLIST_DATA_REQUEST'
export const GET_TODOLIST_DATA = '@@GET_TODOLIST_DATA'
export const IS_AUTHENTIC = '@@IS_AUTHENTIC'
export const IS_AUTHENTIC_REQUEST = '@@IS_AUTHENTIC_REQUEST'
export const LOGOUT = '@@LOGOUT'


